import Navbar from "@/components/Navbar";
import "./globals.css";
import Footer from "@/components/Footer";
import GetStarted from "@/components/GetStarted";

export const metadata = {
  title: "AccessiNor",
  description: "Generated by AccessiNor",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-full">
        <main>
          <Navbar />
          {children}
          <GetStarted />
          <Footer />
        </main>
      </body>
    </html>
  );
}
