import Navbar from "@/components/Navbar";
import "./globals.css";

export const metadata = {
  title: "AccessiNor",
  description: "Generated by AccessiNor",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-full">
        <main>
          <Navbar />
          {children}
          </main>
      </body>
    </html>
  );
}
